Python 3.12.2 (v3.12.2:6abddd9f6a, Feb  6 2024, 17:02:06) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin
Type "help", "copyright", "credits" or "license()" for more information.
>>> # Your Name
... # Date
... # Assignment Name
... # A brief description of the project
... 
... # Prompting the user to enter their first name
... first_name = input("Enter your first name: ")
... 
... # Prompting the user to enter their last name
... last_name = input("Enter your last name: ")
... 
... # Displaying a welcome message
... print("Welcome CTI-110, " + first_name + " " + last_name + "!")
... 
... 
... 
... 
... 
